// material-ui
import { useTheme } from '@mui/material/styles';
import { Alert, AlertTitle, Button, CardContent, Divider, Grid, Modal, Stack } from '@mui/material';
import { useEffect, useState } from 'react';
import { console_log } from 'utils/misc';
import { showToast } from 'utils/utils';
import { useDispatch, useSelector } from 'react-redux';
import MainCard from 'components/MainCard';
import ReactCodeInput from "react-code-input";

const MfaCodeInputModal = (props) => {
    const { show, setShow, title = "", pageData, apiCalling, setApiCalling, submitModalData } = props
    const theme = useTheme();
    const dispatch = useDispatch()
    const userDataStore = useSelector((x) => x.auth);
    const userId = userDataStore?.user?.id
    /////////////////////////////////////////////////////////////////////////////////////////////////////
    const [open, setOpen] = useState(false);
    useEffect(() => {
        if (show) {
            setOpen(true)
        }
    }, [show])

    const handleOpen = () => {
        setOpen(true)
    }
    const handleClose = () => {
        setOpen(false)
        setShow(false)
    }

    const [code, setCode] = useState("");
    const onChangeCode = (v) => {
        console_log(`vvvvvvvvvvv:::`, v)
        setCode(v)
    }
    const submitVerificationCode = () => {
        if (code) {
            submitModalData(code);
        } else {
            showToast("Please input two-step verification code correctly", "error");
        }
    }

    const defaultInputStyle = {
        // fontFamily: 'monospace',
        // MozAppearance: 'textfield',
        // borderRadius: '6px',
        // border: '1px solid',
        // boxShadow: '0px 0px 10px 0px rgba(0,0,0,.10)',
        // margin: '4px',
        // paddingLeft: '8px',
        // paddingRight: 0,
        // width: '36px',
        // height: '42px',
        // fontSize: '32px',
        // boxSizing: 'border-box',
        // color: 'black',
        // backgroundColor: 'white',
        // borderColor: 'lightgrey',
        // textAlign: 'center'

        fontFamily: 'monospace',
        appearance: 'textfield',
        borderRadius: '6px',
        border: '1px solid lightgrey',
        boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 10px 0px',
        margin: '4px',
        paddingLeft: '8px',
        width: '36px',
        height: '42px',
        fontSize: '32px',
        boxSizing: 'border-box',
        color: 'black',
        backgroundColor: 'white'
    }

    const inputStyle = {
        ...defaultInputStyle,
        fontFamily: 'monospace',
        MozAppearance: 'textfield',
        borderRadius: '6px',
        border: '1px solid',
        boxShadow: '0px 0px 10px 0px rgba(0,0,0,.10)',
        margin: '4px',
        paddingLeft: '12px',
        paddingRight: 0,
        width: '54px',
        height: '63px',
        fontSize: '48px',
        boxSizing: 'border-box',
    }

    return (
        <>
            <Modal open={open} onClose={handleClose} aria-labelledby="modal-modal-title" aria-describedby="modal-modal-description" disableAutoFocus={true}>
                <MainCard title={title} modal darkTitle content={false} >
                    <CardContent sx={{ maxWidth: '100%', width: '360px' }}>
                        <Grid container spacing={3} direction="column">
                            <Grid item xs={12} sm={12}>
                                <Alert color="primary" variant="border" icon={false} sx={{ justifyContent: 'center' }}>
                                    <AlertTitle>
                                        Enter the 6-digit code generated by your authenticator app.
                                    </AlertTitle>
                                </Alert>
                            </Grid>
                            <Grid item xs={12} sm={12}>
                                <Stack direction={`row`} justifyContent={`center`} alignItems={`center`} sx={{ py: 1 }}>
                                    <ReactCodeInput
                                        type='number'
                                        fields={6}
                                        value={code}
                                        onChange={onChangeCode}
                                    // inputStyle={inputStyle}
                                    />
                                </Stack>
                            </Grid>
                        </Grid>
                    </CardContent>
                    <Divider />
                    <Stack direction="row" spacing={1} justifyContent="flex-end" sx={{ px: 2.5, py: 2 }}>
                        <Button color="error" size="medium" onClick={handleClose}>
                            Cancel
                        </Button>
                        <Button variant="contained" size="medium" type="button" disabled={apiCalling}
                            onClick={() => submitVerificationCode()}
                        >
                            Submit
                        </Button>
                    </Stack>
                </MainCard>
            </Modal>
        </>
    );
};

export default MfaCodeInputModal;
