import { Request, Response } from 'express'
import { twoFactAuth } from '../../library/twoFactAuth';
import { console_log, empty, get_data_value } from '../../helpers/misc';
import UserBaseController from './user.base.controller';
import { APP_NAME } from '../../var/config';
import { userService } from '../../services/user.service';

export default class UserVerificationController extends UserBaseController {
  constructor() {
    super();
  }

  public init = async (req: Request, res: Response) => {
    this.setReqRes({ req: req, res: res });
    return await this.checkLogin(req, res)
  }

  /**
   * get MFA page detail
   */  
  public getDetail = async (req: Request, res: Response) => {
    try {
      if (empty(await this.init(req, res))) {
        return false
      }
      let post_param: object = req['fields'];
      let get_param: object = req['query'];
      let data = this.data;
      let user = this.user;
      /**************************************************************************************************/
      let two_fact_secret = await twoFactAuth.getGaSecret()
      data['two_fact_secret'] = two_fact_secret
      let two_fact_qr_code_url = await twoFactAuth.getGaQRCode(two_fact_secret, APP_NAME)
      data['two_fact_qr_code_url'] = two_fact_qr_code_url;
      return this.json_output_data(data, "", res);
    } catch (e) {
      console.log("error:::::::::", e)
      return this.json_output_error("", "", res)
    }
  }

  /**
   * complete MFA
   */  
  public completeVerification = async (req: Request, res: Response) => {
    try {
      if (empty(await this.init(req, res))) {
        return false
      }
      let post_param: object = req['fields'];
      let get_param: object = req['query'];
      let data = this.data;
      let user = this.user;
      /**************************************************************************************************/
      console_log(`post_param:::`, post_param)
      let secret = get_data_value(post_param, 'secret'); //This is used to generate QR code
      let otp = get_data_value(post_param, 'otp'); //'385688' ;//Generated by Authenticator.

      const tolerance = 2;
      //Every otp is valid for 30 sec.
      // If somebody provides OTP at 29th sec, by the time it reaches the server OTP is expired.
      //So we can give tolerance =1, it will check current  & previous OTP.
      // tolerance =2, verifies current and last two OTPS
      let checkResult = await twoFactAuth.verifyCode(otp, secret)
      if (checkResult) {
        let condition = { id: user['id'] }
        let update_data = {
          'mfa_status': 3,
          'mfa_secret': secret
        }
        await userService.update(update_data, condition);
        user = await userService.getOne({ id: user['id'] })
        data['user'] = user
        const message = "Two Step Verification is enabled successfully";
        return this.json_output_data(data, message, res);
      } else {
        const message = "Two Step Verification is failed"
        return this.json_output_error(message, "", res)
      }
    } catch (e) {
      console.log("error:::::::::", e)
      return this.json_output_error("", "", res)
    }
  }

  /**
   * cancel MFA
   */  
  public cancelVerification = async (req: Request, res: Response) => {
    try {
      if (empty(await this.init(req, res))) {
        return false
      }
      let post_param: object = req['fields'];
      let get_param: object = req['query'];
      let data = this.data;
      let user = this.user;
      /**************************************************************************************************/
      let condition = { id: user['id'] }
      let update_data = {
        'mfa_status': 0,
        'mfa_secret': ""
      }
      await userService.update(update_data, condition);
      user = await userService.getOne({ id: user['id'] })
      data['user'] = user
      const message = "Two Step Verification has been cancelled";
      return this.json_output_data(data, message, res);
    } catch (e) {
      console.log("error:::::::::", e)
      return this.json_output_error("", "", res)
    }
  }
}

export const userVerificationController = new UserVerificationController()
